# version: '2'
# services:
#   mongo:
#     image: mongo
#     restart: always
#     volumes:
#       - ./data/mongo:/data/db
#     ports:
#       - "27017:27017"
#   fastapi:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     volumes:
#       - './fastapi:/code'
#     ports:
#       - 8000:8000
  #   environment:
  #     MONGODB_URL: mongodb+srv://username:password@cluster0.vdacpkb.mongodb.net/?retryWrites=true&w=majority
  #     PYTHONPATH: /code
  # react:
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    # volumes:
    #   - './farm-react:/app'
    # ports:
    #   - 3000:3000

  
# version: '3.8'
# services:
#   python_backend:
#     container_name: python_cei
#     image: python_cei:0.0.1
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     # environment:
#     #   MONGODB_URL: mongodb+srv://username:password@cluster0.vdacpkb.mongodb.net/?retryWrites=true&w=majority
#     depends_on:
#       - python_db
#   python_db:
#     container_name: python_db
#     image: "mongo"
#     ports:
#       - "27017:27017"
#     volumes:
#       - nps_data:/data/db
# volumes:
#   nps_data: {}
 

version: '3.8'
services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
    ports:
      - 3000:3000    